### ISSUE TITLE
Figure out how to convey the behavior of ops when receiving different Tensor subclasses

### ISSUE THREAD

**Issue by pranavm-nvidia** [NVIDIA/TensorRT-Incubator#226]
For example, `/` will return `ShapeScalar` if all inputs are `ShapeScalar`s, `Shape` if any inputs are `Shape`, and `Tensor` otherwise. This is determined by `infer_shape_output_idxs`, but we don't currently convey that information through the API.

Ideally, in 99% of cases, you don't actually care about the subclass of what you're manipulating - `Shape` behaves like a list and `ShapeScalar` behaves like a Python number. However, if we can figure out a way to report the behavior without duplicating logic, that would improve the comprehensiveness of the documentation.

**Comment by slyubomirsky** [comment]
The main thing that causes an issue here is that `Shape` has different behavior for overloads, which can lead to surprising results when passing `Shape`s where `Tensor`s or vice versa are otherwise expected (contradicting the usual recommendations for inheritance in object-oriented design). To prevent unwelcome surprises, I think it might be reasonable not to permit `Shape`s and `Tensor`s to mix without explicit conversions.

`ShapeScalar`, to my understanding, is really supposed to be "invisible" to the user, existing only for convenience in shape inference, so for that one, an approach like that in #224 of adding rules that would silently determine when to keep the type or not is reasonable.

**Comment by slyubomirsky** [comment]
As for how to convey this in the documentation, would stating it in the top-level doc comments for `Shape` and `ShapeScalar` not suffice?

**Comment by pranavm-nvidia** [comment]
> As for how to convey this in the documentation, would stating it in the top-level doc comments for `Shape` and `ShapeScalar` not suffice?

It may need to be on a per-operator basis, since different ops could presumably have different behavior. For example, in Slice, you can freely mix `Tensor`s and `ShapeScalar`s in the index argument without affecting the output type, while for binary operations, the types of the inputs directly determine the output type.

**Comment by slyubomirsky** [comment]
That is true. I think the exceptions to the rule are uncommon enough that we can just document it in each op and keep it as a general practice that if an op changes its `infer_shape_output_idxs` method, there should be a comment about the behavior. If we insist on mechanically enforcing that there are comments, we could check if there is a comment on `infer_shape_output_idxs` and use that to generate a message, but I think that might be overkill unless we start to have a lot more exceptions.

**Comment by pranavm-nvidia** [comment]
No longer applicable as we dropped `Shape`.
