### ISSUE TITLE
Disallow mixing Tensor/Shape types in operations

### ISSUE THREAD

**Issue by pranavm-nvidia** [NVIDIA/TensorRT-Incubator#233]
The behavior of some operations, e.g. binary elementwise, is not obvious when mixing `Tensor`/`Shape` types. We may want to disallow mixing types in such cases. See https://github.com/NVIDIA/TensorRT-Incubator/pull/224#discussion_r1777700616 for more context.

**Comment by pranavm-nvidia** [comment]
Other TODOs:
- 
- Rename/refactor `infer_shape_output_idxs` to better reflect it's purpose of also reporting on `ShapeScalar`s.

**Comment by slyubomirsky** [comment]
We might want to decide on the terminology to use here, for what to call the variants of `Tensor`. "Tensor types" might work, but it seems too easily confused with datatypes. Maybe "tensor variants"?

Currently, the vast majority of uses of `convert_inputs_to_tensors` are for binary elementwise ops (the only other is for `slice_helper`), where combining `Shape`s with `Tensor`s could cause confusion. (By contrast, I doubt that combining `ShapeScalar`s with `Tensor`s or `Shape`s is likely to cause confusion). Since there are relatively few uses, perhaps we could just have a flag for disallowing combining different tensor variants? The error could give a hint to have an explicit conversion if that's what the user really wants (which is what we do for several of the `Shape` methods already). The downside is that it might be a little clumsy to require explicit conversions, but I'm not sure there is any reason to believe that combining `Tensor`s and `Shape`s is something that would be commonly needed. (We could see if it happens in any of our examples.)

Incidentally, for `slice_helper`, I would argue that mixing tensor variants is unlikely to be indicative of an error, since the decorator would only be checking the _index_ arguments.

**Comment by slyubomirsky** [comment]
Closing because we eliminated `Shape`s altogether.
